import React from 'react'
import CreatePage from 'modules/Studio'

const metadata = {
  title: 'Meme Studio',
  description: 'Generated by create next app'
}

const Page = () => {
  return <CreatePage />
}

export { metadata }

export default Page
