// Default
export const SET_ON_STUDIO = 'SET_ON_STUDIO'
export const SET_MEMES = 'SET_MEMES'
export const SET_CURSOR_MEMES = 'SET_CURSOR_MEMES'
export const SET_HAS_NEXT_MEMES = 'SET_HAS_NEXT_MEMES'

// Editor
export const SET_TEXT_ID_SELECTED = 'SET_TEXT_ID_SELECTED'
export const SET_SHOW_TEXT_AREAS = 'SET_SHOW_TEXT_AREAS'
export const SET_MEME_SELECTED = 'SET_MEME_SELECTED'
export const SET_CANVAS = 'SET_CANVAS'
export const SET_TEXTS = 'SET_TEXTS'
export const SET_DRAW_PROPERTIES = 'SET_DRAW_PROPERTIES'
