import React from 'react'
import CreatePage from 'modules/Studio'
import { getMeme, getMemes } from '@shared/api/memes'

const metadata = {
  title: 'Meme Studio',
  description: 'Generated by create next app'
}

export async function generateStaticParams() {
  const memes = await getMemes()

  return memes.map((meme) => {
    return {
      id: meme.id
    }
  })
}

const Page = async ({ params }: { params: { id: string } }) => {
  const meme = await getMeme(params.id)

  console.log(meme)

  if (meme) {
    return <CreatePage meme={meme.meme} textboxes={meme.textboxes} />
  }

  return <CreatePage />
}

export { metadata }

export default Page
